# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

# Controls when the action will run. Triggers the workflow on pushes into rc branch.
on:
  push:
    branches: "rc"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2
    
    # Install Java 11
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    # Build with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
    # Upload the artifact
    - name: Upload the artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: stan-core.jar
        path: target/*.jar
